import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import {
  createLocalGeneratedMediaResponse,
  createLocalGeneratedMediaStore,
} from "./local-media-store";

const temporaryDirectories: string[] = [];

afterEach(async () => {
  await Promise.all(temporaryDirectories.splice(0).map((directory) => rm(directory, {
    force: true,
    recursive: true,
  })));
});

async function temporaryStore() {
  const directory = await mkdtemp(join(tmpdir(), "vanillasky-media-store-test-"));
  temporaryDirectories.push(directory);
  return createLocalGeneratedMediaStore({ directory });
}

describe("local generated media storage", () => {
  it("stores generated bytes behind a local URL instead of exposing provider URLs", async () => {
    const store = await temporaryStore();
    const stored = await store.write({
      data: new Uint8Array([1, 2, 3, 4]),
      mediaType: "video/mp4",
      kind: "video",
      idempotencyKey: "run-1:scene-2",
    });

    expect(stored.url).toMatch(/^\/api\/channel-media\/[a-f0-9]{24}\.mp4$/);
    const filename = stored.url.split("/").at(-1)!;
    const response = await createLocalGeneratedMediaResponse({
      directory: store.directory,
      filename,
      request: new Request(`http://localhost${stored.url}`),
    });

    expect(response.status).toBe(200);
    expect(response.headers.get("content-type")).toBe("video/mp4");
    expect([...new Uint8Array(await response.arrayBuffer())]).toEqual([1, 2, 3, 4]);
  });

  it("supports byte ranges required by browser video playback", async () => {
    const store = await temporaryStore();
    const stored = await store.write({
      data: new Uint8Array([10, 20, 30, 40, 50]),
      mediaType: "video/mp4",
      kind: "video",
      idempotencyKey: "run-2:scene-1",
    });
    const filename = stored.url.split("/").at(-1)!;
    const response = await createLocalGeneratedMediaResponse({
      directory: store.directory,
      filename,
      request: new Request(`http://localhost${stored.url}`, {
        headers: { Range: "bytes=1-3" },
      }),
    });

    expect(response.status).toBe(206);
    expect(response.headers.get("content-range")).toBe("bytes 1-3/5");
    expect([...new Uint8Array(await response.arrayBuffer())]).toEqual([20, 30, 40]);
  });

  it("rejects traversal and unknown media extensions", async () => {
    const store = await temporaryStore();
    const response = await createLocalGeneratedMediaResponse({
      directory: store.directory,
      filename: "../secrets.env",
      request: new Request("http://localhost/api/channel-media/secrets.env"),
    });

    expect(response.status).toBe(404);
  });
});
