// Generated by `vanillasky sync`. Do not edit.
import { createTemplateRegistry } from "@vanillaskyai/video/templates";
import { template as template0 } from "./templates/animated-sticker";
import { template as template1 } from "./templates/generated-scene";
import { template as template2 } from "./templates/lottie-motion";

export const definitions = [template0, template1, template2];
export const templates = createTemplateRegistry({ definitions });
