// Generated by `vanillasky sync`. Do not edit.
import { createServerTemplateRegistry } from "@vanillaskyai/video/server";
import type { ServerTemplateMetadata } from "@vanillaskyai/video/server";

const templateMetadata: ServerTemplateMetadata[] = [
  {
    "label": "Animated sticker",
    "description": "A transparent GIF accent decoded into seekable frames.",
    "usesGlobalTextEffect": false,
    "usesGlobalTransition": false,
    "usesGlobalBackgroundEffect": false,
    "id": "animatedSticker",
    "family": "Media & motion",
    "jobs": [
      "punctuation",
      "payoff"
    ],
    "register": "motion-led",
    "useWhen": "Use as a short reaction, celebration, transition accent, or shareable visual punchline.",
    "avoidWhen": "Avoid when the animation would compete with evidence or needs photoreal detail.",
    "minDuration": 3,
    "preferredDuration": 5,
    "schema": {
      "type": "object",
      "properties": {
        "stickerKey": {
          "type": "string",
          "enum": [
            "spark",
            "rocket",
            "confetti",
            "launch"
          ],
          "title": "Sticker choice"
        },
        "decisionReason": {
          "type": "string",
          "minLength": 8,
          "maxLength": 140,
          "title": "Why this treatment fits"
        },
        "headline": {
          "type": "string",
          "minLength": 1,
          "maxLength": 56,
          "default": "Make the payoff pop."
        },
        "caption": {
          "type": "string",
          "minLength": 1,
          "maxLength": 100,
          "default": "Transparent reactions without losing deterministic playback."
        }
      },
      "required": [
        "stickerKey",
        "decisionReason",
        "headline",
        "caption"
      ],
      "additionalProperties": false
    }
  },
  {
    "label": "Generated scene",
    "description": "A generated portrait image with grounded launch copy.",
    "usesGlobalTextEffect": false,
    "usesGlobalTransition": false,
    "usesGlobalBackgroundEffect": false,
    "id": "generatedScene",
    "family": "Media & motion",
    "jobs": [
      "setup",
      "atmosphere",
      "claim",
      "payoff"
    ],
    "register": "motion-led",
    "useWhen": "Use when a unique scene image makes the idea concrete or emotionally memorable.",
    "avoidWhen": "Avoid when supplied evidence, product UI, or exact data should remain the focus.",
    "minDuration": 4,
    "preferredDuration": 6,
    "schema": {
      "type": "object",
      "properties": {
        "imageBrief": {
          "type": "string",
          "minLength": 12,
          "maxLength": 240,
          "title": "Image generation brief"
        },
        "imageUrl": {
          "type": "string",
          "format": "uri",
          "title": "Host-resolved image"
        },
        "decisionReason": {
          "type": "string",
          "minLength": 8,
          "maxLength": 140,
          "title": "Why this treatment fits"
        },
        "eyebrow": {
          "type": "string",
          "maxLength": 40,
          "default": "AI-GENERATED SCENE"
        },
        "headline": {
          "type": "string",
          "minLength": 1,
          "maxLength": 72,
          "default": "Turn one idea into a world."
        }
      },
      "required": [
        "imageBrief",
        "decisionReason",
        "eyebrow",
        "headline"
      ],
      "additionalProperties": false
    }
  },
  {
    "label": "Lottie motion",
    "description": "A small vector motion asset whose frame follows scene progress.",
    "usesGlobalTextEffect": false,
    "usesGlobalTransition": false,
    "usesGlobalBackgroundEffect": false,
    "id": "lottieMotion",
    "family": "Media & motion",
    "jobs": [
      "setup",
      "punctuation",
      "payoff"
    ],
    "register": "motion-led",
    "useWhen": "Use for branded loops, icons, explainers, progress states, and lightweight reusable motion.",
    "avoidWhen": "Avoid for photographic storytelling or when a static icon communicates the same idea.",
    "minDuration": 3,
    "preferredDuration": 5,
    "schema": {
      "type": "object",
      "properties": {
        "motionKey": {
          "type": "string",
          "enum": [
            "orbit",
            "pulse",
            "steps"
          ],
          "title": "Motion choice"
        },
        "decisionReason": {
          "type": "string",
          "minLength": 8,
          "maxLength": 140,
          "title": "Why this treatment fits"
        },
        "kicker": {
          "type": "string",
          "minLength": 1,
          "maxLength": 36,
          "default": "VECTOR MOTION"
        },
        "headline": {
          "type": "string",
          "minLength": 1,
          "maxLength": 64,
          "default": "Tiny asset. Big energy."
        }
      },
      "required": [
        "motionKey",
        "decisionReason",
        "kicker",
        "headline"
      ],
      "additionalProperties": false
    }
  }
];
export const templates = createServerTemplateRegistry({ templates: templateMetadata });
