// Generated by `vanillasky templates sync`. Do not edit.
import { createTemplateRegistry } from "@vanillaskyai/video/templates";
import { barChartTemplate as template0 } from "./templates/barChart";
import { bigNumberTemplate as template1 } from "./templates/bigNumber";
import { cardListTemplate as template2 } from "./templates/cardList";
import { mediaTemplate as template3 } from "./templates/media";
import { milestoneTemplate as template4 } from "./templates/milestone";
import { stepsTemplate as template5 } from "./templates/steps";
import { tripleStatsTemplate as template6 } from "./templates/tripleStats";

export const definitions = [template0, template1, template2, template3, template4, template5, template6];
export const templates = createTemplateRegistry({ definitions });
