// Generated by `vanillasky templates sync`. Do not edit.
import { createServerTemplateRegistry } from "@vanillaskyai/video/server";
import type { ServerTemplateMetadata } from "@vanillaskyai/video/server";

const templateMetadata: ServerTemplateMetadata[] = [
  {
    "label": "Bar chart",
    "description": "Animated labeled bars compare grounded values beneath a headline.",
    "usesGlobalTextEffect": false,
    "usesGlobalTransition": true,
    "usesGlobalBackgroundEffect": true,
    "id": "barChart",
    "family": "Data & metrics",
    "jobs": [
      "proof"
    ],
    "register": "motion-led",
    "useWhen": "Two or more grounded labeled values need a readable comparison, ranking, or relative-size view.",
    "avoidWhen": "Labels or exact values are missing, one metric is the hero, or the data represents progress toward a whole.",
    "transitionTiming": {
      "entryReadyProgress": 0.2,
      "holdProgress": 0.7
    },
    "textCanvas": "tight",
    "minDuration": 2,
    "preferredDuration": 4,
    "timing": {
      "contentFields": [
        "bars"
      ],
      "contentUnit": "items"
    },
    "schema": {
      "type": "object",
      "properties": {
        "texts": {
          "type": "string",
          "title": "Text",
          "description": "Title text shown above the chart",
          "default": "Revenue up 300%."
        },
        "bars": {
          "type": "array",
          "title": "Comparison values",
          "description": "Array of 2-6 grounded values with short category labels. Values are shown exactly and bar heights are scaled relative to the largest value. Use only facts supported by the input.",
          "examples": [
            [
              {
                "label": "Free",
                "value": 24
              },
              {
                "label": "Pro",
                "value": 61
              },
              {
                "label": "Business",
                "value": 88
              }
            ]
          ],
          "items": {
            "type": "object",
            "properties": {
              "label": {
                "type": "string",
                "description": "Short category label shown below the bar (18 characters or fewer).",
                "maxLength": 18
              },
              "value": {
                "type": "number",
                "description": "Exact grounded value shown above the bar.",
                "format": "grounded-stat",
                "minimum": 0
              }
            },
            "required": [
              "label",
              "value"
            ],
            "additionalProperties": false
          },
          "minItems": 2,
          "maxItems": 6,
          "default": [
            {
              "label": "Q1",
              "value": 42
            },
            {
              "label": "Q2",
              "value": 58
            },
            {
              "label": "Q3",
              "value": 76
            },
            {
              "label": "Q4",
              "value": 91
            }
          ]
        },
        "mediaUrl": {
          "type": "string",
          "title": "Background media",
          "description": "Optional photo or video URL behind this scene. When set, replaces the brand gradient.",
          "format": "uri",
          "default": ""
        },
        "mediaKeyword": {
          "type": "string",
          "title": "Background search keyword",
          "description": "2-4 word English term for Pexels stock-footage search (auto-fills mediaUrl).",
          "format": "stock-media-keyword",
          "default": ""
        },
        "mediaType": {
          "type": "string",
          "title": "Background media type",
          "description": "auto detects photo/video from URL. 'gradient' is a deliberate mode — atmospheric brand-color scene with no stock footage.",
          "enum": [
            "auto",
            "photo",
            "video",
            "gradient"
          ],
          "default": "auto"
        },
        "mediaPoster": {
          "type": "string",
          "title": "Background poster image",
          "description": "Still image URL shown while a video backdrop is decoding its first frame. Auto-filled from Pexels' thumbnail when fillPexelsUrls sets a video mediaUrl. Hides the gradient flash that would otherwise appear in the ~50–400ms gap between a <video> mounting and decoding its first frame.",
          "format": "uri",
          "default": ""
        },
        "mediaPosition": {
          "type": "string",
          "title": "Background focal position",
          "description": "Controls which part of a photo or video stays visible when cover-cropped. Pick the subject's side or vertical anchor after inspecting the frame.",
          "enum": [
            "center",
            "top",
            "bottom",
            "left",
            "right"
          ],
          "default": "center"
        },
        "mediaTreatment": {
          "type": "string",
          "title": "Background contrast treatment",
          "description": "none leaves the picture untouched, for a scene carrying no type; subtle preserves a visual hero; cinematic adds balanced contrast; text-safe adds a stronger wash for copy-heavy scenes.",
          "enum": [
            "none",
            "subtle",
            "cinematic",
            "text-safe"
          ],
          "default": "cinematic"
        }
      },
      "required": [
        "texts",
        "bars"
      ],
      "additionalProperties": false,
      "x-vanillasky": {
        "requiresStat": true,
        "allowsStockMedia": true
      }
    }
  },
  {
    "label": "Big number",
    "description": "A single animated count-up metric with headline and label.",
    "usesGlobalTextEffect": false,
    "usesGlobalTransition": true,
    "usesGlobalBackgroundEffect": true,
    "id": "bigNumber",
    "family": "Data & metrics",
    "jobs": [
      "claim",
      "proof"
    ],
    "register": "typography-led",
    "useWhen": "One exact grounded number is the hero: growth, speed, rank, customer count, or reduction.",
    "avoidWhen": "No exact number is supplied, three peer values matter equally, or the value means completion progress.",
    "transitionTiming": {
      "entryReadyProgress": 0.2,
      "holdProgress": 0.7
    },
    "textCanvas": "tight",
    "minDuration": 1.5,
    "preferredDuration": 4,
    "timing": {
      "contentFields": [
        "texts",
        "label"
      ],
      "contentUnit": "words"
    },
    "schema": {
      "type": "object",
      "properties": {
        "texts": {
          "type": "string",
          "title": "Text",
          "description": "Concise title shown above the metric (48 characters maximum).",
          "minLength": 1,
          "maxLength": 48,
          "default": "Our biggest milestone yet."
        },
        "value": {
          "type": "number",
          "title": "Target number",
          "description": "The number to count up to",
          "default": 1000
        },
        "decimalPlaces": {
          "type": "number",
          "title": "Decimal places",
          "description": "Optional display precision; when omitted, precision is inferred from the value"
        },
        "confetti": {
          "type": "boolean",
          "title": "Celebrate with confetti",
          "description": "Add a confetti burst when the metric is explicitly celebratory",
          "default": false
        },
        "label": {
          "type": "string",
          "title": "Label",
          "description": "Short label displayed below the number (32 characters maximum).",
          "minLength": 1,
          "maxLength": 32,
          "default": "Total users"
        },
        "prefix": {
          "type": "string",
          "title": "Prefix",
          "description": "Compact prefix before the number (e.g. $, €; 2 characters maximum).",
          "maxLength": 2,
          "default": ""
        },
        "unit": {
          "type": "string",
          "title": "Unit suffix",
          "description": "Compact suffix after the number (e.g. %, +, k, M; 4 characters maximum).",
          "maxLength": 4,
          "default": ""
        },
        "mediaUrl": {
          "type": "string",
          "title": "Background media",
          "description": "Optional photo or video URL behind this scene. When set, replaces the brand gradient.",
          "format": "uri",
          "default": ""
        },
        "mediaKeyword": {
          "type": "string",
          "title": "Background search keyword",
          "description": "2-4 word English term for Pexels stock-footage search (auto-fills mediaUrl).",
          "format": "stock-media-keyword",
          "default": ""
        },
        "mediaType": {
          "type": "string",
          "title": "Background media type",
          "description": "auto detects photo/video from URL. 'gradient' is a deliberate mode — atmospheric brand-color scene with no stock footage.",
          "enum": [
            "auto",
            "photo",
            "video",
            "gradient"
          ],
          "default": "auto"
        },
        "mediaPoster": {
          "type": "string",
          "title": "Background poster image",
          "description": "Still image URL shown while a video backdrop is decoding its first frame. Auto-filled from Pexels' thumbnail when fillPexelsUrls sets a video mediaUrl. Hides the gradient flash that would otherwise appear in the ~50–400ms gap between a <video> mounting and decoding its first frame.",
          "format": "uri",
          "default": ""
        },
        "mediaPosition": {
          "type": "string",
          "title": "Background focal position",
          "description": "Controls which part of a photo or video stays visible when cover-cropped. Pick the subject's side or vertical anchor after inspecting the frame.",
          "enum": [
            "center",
            "top",
            "bottom",
            "left",
            "right"
          ],
          "default": "center"
        },
        "mediaTreatment": {
          "type": "string",
          "title": "Background contrast treatment",
          "description": "none leaves the picture untouched, for a scene carrying no type; subtle preserves a visual hero; cinematic adds balanced contrast; text-safe adds a stronger wash for copy-heavy scenes.",
          "enum": [
            "none",
            "subtle",
            "cinematic",
            "text-safe"
          ],
          "default": "cinematic"
        }
      },
      "required": [
        "texts",
        "value",
        "label"
      ],
      "additionalProperties": false,
      "x-vanillasky": {
        "requiresStat": true,
        "allowsStockMedia": true
      }
    }
  },
  {
    "label": "Card list",
    "description": "Two or three parallel facts appear as stacked icon cards beneath a headline.",
    "usesGlobalTextEffect": false,
    "usesGlobalTransition": true,
    "usesGlobalBackgroundEffect": true,
    "id": "cardList",
    "family": "Explainers",
    "jobs": [
      "proof"
    ],
    "register": "card-led",
    "useWhen": "Two or three grounded features, benefits, use cases, integrations, or parallel facts need structure.",
    "avoidWhen": "The facts are sequential, fewer than two exist, or one idea deserves the whole scene.",
    "transitionTiming": {
      "entryReadyProgress": 0.2,
      "holdProgress": 0.7
    },
    "textCanvas": "tight",
    "minDuration": 2,
    "preferredDuration": 3.5,
    "timing": {
      "contentFields": [
        "items"
      ],
      "contentUnit": "items"
    },
    "schema": {
      "type": "object",
      "properties": {
        "texts": {
          "type": "string",
          "title": "Text",
          "description": "Title text",
          "default": "What you get."
        },
        "items": {
          "type": "array",
          "title": "Features",
          "description": "JSON array of 2 or 3 feature descriptions. Send only the facts the evidence supports — never pad the list to reach three. Items often contain commas, so send an array rather than comma-joined text.",
          "items": {
            "type": "string"
          },
          "minItems": 2,
          "maxItems": 3,
          "default": [
            "Automate your savings on energy bills",
            "Cleaner energy without raising your bill",
            "Same account and service guaranteed"
          ]
        },
        "itemEmojis": {
          "type": "array",
          "title": "Feature emojis",
          "description": "JSON array of emojis, one per feature row (optional). Rows without an emoji fall back to ✦.",
          "examples": [
            [
              "💰",
              "⚡",
              "🔒"
            ]
          ],
          "items": {
            "type": "string"
          },
          "maxItems": 3,
          "default": []
        },
        "mediaUrl": {
          "type": "string",
          "title": "Background media",
          "description": "Optional photo or video URL behind this scene. When set, replaces the brand gradient.",
          "format": "uri",
          "default": ""
        },
        "mediaKeyword": {
          "type": "string",
          "title": "Background search keyword",
          "description": "2-4 word English term for Pexels stock-footage search (auto-fills mediaUrl).",
          "format": "stock-media-keyword",
          "default": ""
        },
        "mediaType": {
          "type": "string",
          "title": "Background media type",
          "description": "auto detects photo/video from URL. 'gradient' is a deliberate mode — atmospheric brand-color scene with no stock footage.",
          "enum": [
            "auto",
            "photo",
            "video",
            "gradient"
          ],
          "default": "auto"
        },
        "mediaPoster": {
          "type": "string",
          "title": "Background poster image",
          "description": "Still image URL shown while a video backdrop is decoding its first frame. Auto-filled from Pexels' thumbnail when fillPexelsUrls sets a video mediaUrl. Hides the gradient flash that would otherwise appear in the ~50–400ms gap between a <video> mounting and decoding its first frame.",
          "format": "uri",
          "default": ""
        },
        "mediaPosition": {
          "type": "string",
          "title": "Background focal position",
          "description": "Controls which part of a photo or video stays visible when cover-cropped. Pick the subject's side or vertical anchor after inspecting the frame.",
          "enum": [
            "center",
            "top",
            "bottom",
            "left",
            "right"
          ],
          "default": "center"
        },
        "mediaTreatment": {
          "type": "string",
          "title": "Background contrast treatment",
          "description": "none leaves the picture untouched, for a scene carrying no type; subtle preserves a visual hero; cinematic adds balanced contrast; text-safe adds a stronger wash for copy-heavy scenes.",
          "enum": [
            "none",
            "subtle",
            "cinematic",
            "text-safe"
          ],
          "default": "cinematic"
        }
      },
      "required": [
        "texts",
        "items"
      ],
      "additionalProperties": false,
      "x-vanillasky": {
        "allowsStockMedia": true
      }
    }
  },
  {
    "label": "Full-bleed media",
    "description": "Full-bleed photo, video, or brand gradient with a centered headline.",
    "usesGlobalTextEffect": true,
    "usesGlobalTransition": true,
    "usesGlobalBackgroundEffect": true,
    "id": "media",
    "family": "Media & motion",
    "jobs": [
      "setup",
      "atmosphere",
      "payoff"
    ],
    "register": "motion-led",
    "useWhen": "A visual hook, scenic beat, or concrete product-context line benefits from immersive media.",
    "avoidWhen": "The scene needs structured facts, exact comparisons, a device frame, or attributed proof.",
    "transitionTiming": {
      "entryReadyProgress": 0.2,
      "holdProgress": 0.7
    },
    "textCanvas": "open",
    "minDuration": 1,
    "preferredDuration": 2,
    "timing": {
      "contentFields": [
        "texts"
      ],
      "contentUnit": "words"
    },
    "schema": {
      "type": "object",
      "properties": {
        "texts": {
          "type": "string",
          "title": "Text",
          "description": "Title text shown on the scene",
          "default": "Make an impact."
        },
        "mediaUrl": {
          "type": "string",
          "title": "Background media",
          "description": "Optional photo or video URL behind this scene. When set, replaces the brand gradient.",
          "format": "uri",
          "default": ""
        },
        "mediaKeyword": {
          "type": "string",
          "title": "Background search keyword",
          "description": "2-4 word English term for Pexels stock-footage search (auto-fills mediaUrl).",
          "format": "stock-media-keyword",
          "default": ""
        },
        "mediaType": {
          "type": "string",
          "title": "Background media type",
          "description": "auto detects photo/video from URL. 'gradient' is a deliberate mode — atmospheric brand-color scene with no stock footage.",
          "enum": [
            "auto",
            "photo",
            "video",
            "gradient"
          ],
          "default": "auto"
        },
        "mediaPoster": {
          "type": "string",
          "title": "Background poster image",
          "description": "Still image URL shown while a video backdrop is decoding its first frame. Auto-filled from Pexels' thumbnail when fillPexelsUrls sets a video mediaUrl. Hides the gradient flash that would otherwise appear in the ~50–400ms gap between a <video> mounting and decoding its first frame.",
          "format": "uri",
          "default": ""
        },
        "mediaPosition": {
          "type": "string",
          "title": "Background focal position",
          "description": "Controls which part of a photo or video stays visible when cover-cropped. Pick the subject's side or vertical anchor after inspecting the frame.",
          "enum": [
            "center",
            "top",
            "bottom",
            "left",
            "right"
          ],
          "default": "center"
        },
        "mediaTreatment": {
          "type": "string",
          "title": "Background contrast treatment",
          "description": "none leaves the picture untouched, for a scene carrying no type; subtle preserves a visual hero; cinematic adds balanced contrast; text-safe adds a stronger wash for copy-heavy scenes.",
          "enum": [
            "none",
            "subtle",
            "cinematic",
            "text-safe"
          ],
          "default": "cinematic"
        },
        "confetti": {
          "type": "boolean",
          "title": "Confetti",
          "description": "Layer falling confetti particles over the backdrop. Set true when the copy is celebratory (launch, milestone, win, anniversary, achievement). Works on top of any mediaType — photo, video, or gradient.",
          "default": false
        }
      },
      "required": [
        "texts"
      ],
      "additionalProperties": false,
      "x-vanillasky": {
        "allowsStockMedia": true
      }
    }
  },
  {
    "label": "Milestone",
    "description": "A large count-up achievement with an optional celebratory badge.",
    "usesGlobalTextEffect": false,
    "usesGlobalTransition": false,
    "usesGlobalBackgroundEffect": false,
    "id": "milestone",
    "family": "Data & metrics",
    "jobs": [
      "proof",
      "payoff"
    ],
    "register": "typography-led",
    "useWhen": "An exact grounded achievement count marks users, revenue, years, installs, customers, or adoption.",
    "avoidWhen": "The value is a release number, price, unbounded percentage, or not an achievement count.",
    "textCanvas": "open",
    "minDuration": 2.5,
    "preferredDuration": 4,
    "timing": {
      "contentFields": [
        "label",
        "badgeText"
      ],
      "contentUnit": "words"
    },
    "schema": {
      "type": "object",
      "properties": {
        "label": {
          "type": "string",
          "title": "Label",
          "description": "Short label above the number (e.g. Followers, Subscribers, Downloads; 32 characters maximum).",
          "minLength": 1,
          "maxLength": 32,
          "default": "Followers"
        },
        "targetNumber": {
          "type": "number",
          "title": "Target number",
          "description": "The milestone number to reach",
          "default": 10000
        },
        "startNumber": {
          "type": "number",
          "title": "Start number",
          "description": "Number the counter starts rolling from. Defaults to 0.",
          "default": 0
        },
        "badgeText": {
          "type": "string",
          "title": "Badge text",
          "description": "Concise celebration badge text that pops in at the milestone (32 characters maximum).",
          "maxLength": 32,
          "examples": [
            "10K Followers!"
          ],
          "default": ""
        },
        "badgeEmoji": {
          "type": "string",
          "title": "Badge emoji",
          "description": "Emoji shown in the celebration badge",
          "format": "emoji",
          "maxLength": 16,
          "default": "🎉"
        },
        "mediaUrl": {
          "type": "string",
          "title": "Background media",
          "description": "Optional photo or video URL behind this scene. When set, replaces the brand gradient.",
          "format": "uri",
          "default": ""
        },
        "mediaKeyword": {
          "type": "string",
          "title": "Background search keyword",
          "description": "2-4 word English term for Pexels stock-footage search (auto-fills mediaUrl).",
          "format": "stock-media-keyword",
          "default": ""
        },
        "mediaType": {
          "type": "string",
          "title": "Background media type",
          "description": "auto detects photo/video from URL. 'gradient' is a deliberate mode — atmospheric brand-color scene with no stock footage.",
          "enum": [
            "auto",
            "photo",
            "video",
            "gradient"
          ],
          "default": "auto"
        },
        "mediaPoster": {
          "type": "string",
          "title": "Background poster image",
          "description": "Still image URL shown while a video backdrop is decoding its first frame. Auto-filled from Pexels' thumbnail when fillPexelsUrls sets a video mediaUrl. Hides the gradient flash that would otherwise appear in the ~50–400ms gap between a <video> mounting and decoding its first frame.",
          "format": "uri",
          "default": ""
        },
        "mediaPosition": {
          "type": "string",
          "title": "Background focal position",
          "description": "Controls which part of a photo or video stays visible when cover-cropped. Pick the subject's side or vertical anchor after inspecting the frame.",
          "enum": [
            "center",
            "top",
            "bottom",
            "left",
            "right"
          ],
          "default": "center"
        },
        "mediaTreatment": {
          "type": "string",
          "title": "Background contrast treatment",
          "description": "none leaves the picture untouched, for a scene carrying no type; subtle preserves a visual hero; cinematic adds balanced contrast; text-safe adds a stronger wash for copy-heavy scenes.",
          "enum": [
            "none",
            "subtle",
            "cinematic",
            "text-safe"
          ],
          "default": "cinematic"
        }
      },
      "required": [
        "label",
        "targetNumber"
      ],
      "additionalProperties": false,
      "x-vanillasky": {
        "requiresStat": true,
        "allowsStockMedia": true
      }
    }
  },
  {
    "label": "Steps",
    "description": "Two or three ordered workflow steps reveal as a vertical sequence.",
    "usesGlobalTextEffect": false,
    "usesGlobalTransition": true,
    "usesGlobalBackgroundEffect": true,
    "id": "steps",
    "family": "Explainers",
    "jobs": [
      "setup",
      "proof"
    ],
    "register": "card-led",
    "useWhen": "Two or three grounded actions form a real sequence, workflow, or how-it-works explanation.",
    "avoidWhen": "Order does not matter, fewer than two steps exist, or the content is a parallel feature list.",
    "transitionTiming": {
      "entryReadyProgress": 0.2,
      "holdProgress": 0.7
    },
    "textCanvas": "tight",
    "minDuration": 2,
    "preferredDuration": 3.5,
    "timing": {
      "contentFields": [
        "steps"
      ],
      "contentUnit": "items"
    },
    "schema": {
      "type": "object",
      "properties": {
        "texts": {
          "type": "string",
          "title": "Text",
          "description": "Title text",
          "default": "How it works."
        },
        "steps": {
          "type": "array",
          "title": "Steps",
          "description": "JSON array of 2 or 3 step labels. Send only the steps the evidence supports — never pad the sequence to reach three. Keep each label to 1-2 words and at most 18 characters. Send as an array so labels with internal punctuation render correctly. Example: [\"Capture\", \"Detect\", \"Notify\"]",
          "items": {
            "type": "string"
          },
          "minItems": 2,
          "maxItems": 3,
          "default": [
            "Describe",
            "Preview",
            "Export"
          ]
        },
        "stepEmojis": {
          "type": "array",
          "title": "Step emojis",
          "description": "JSON array of emojis, one per step (optional). Leave empty for numbered circles. Example: [\"✍️\", \"👀\", \"🚀\"]",
          "examples": [
            [
              "✍️",
              "👀",
              "🚀"
            ]
          ],
          "items": {
            "type": "string"
          },
          "maxItems": 3,
          "default": []
        },
        "mediaUrl": {
          "type": "string",
          "title": "Background media",
          "description": "Optional photo or video URL behind this scene. When set, replaces the brand gradient.",
          "format": "uri",
          "default": ""
        },
        "mediaKeyword": {
          "type": "string",
          "title": "Background search keyword",
          "description": "2-4 word English term for Pexels stock-footage search (auto-fills mediaUrl).",
          "format": "stock-media-keyword",
          "default": ""
        },
        "mediaType": {
          "type": "string",
          "title": "Background media type",
          "description": "auto detects photo/video from URL. 'gradient' is a deliberate mode — atmospheric brand-color scene with no stock footage.",
          "enum": [
            "auto",
            "photo",
            "video",
            "gradient"
          ],
          "default": "auto"
        },
        "mediaPoster": {
          "type": "string",
          "title": "Background poster image",
          "description": "Still image URL shown while a video backdrop is decoding its first frame. Auto-filled from Pexels' thumbnail when fillPexelsUrls sets a video mediaUrl. Hides the gradient flash that would otherwise appear in the ~50–400ms gap between a <video> mounting and decoding its first frame.",
          "format": "uri",
          "default": ""
        },
        "mediaPosition": {
          "type": "string",
          "title": "Background focal position",
          "description": "Controls which part of a photo or video stays visible when cover-cropped. Pick the subject's side or vertical anchor after inspecting the frame.",
          "enum": [
            "center",
            "top",
            "bottom",
            "left",
            "right"
          ],
          "default": "center"
        },
        "mediaTreatment": {
          "type": "string",
          "title": "Background contrast treatment",
          "description": "none leaves the picture untouched, for a scene carrying no type; subtle preserves a visual hero; cinematic adds balanced contrast; text-safe adds a stronger wash for copy-heavy scenes.",
          "enum": [
            "none",
            "subtle",
            "cinematic",
            "text-safe"
          ],
          "default": "cinematic"
        }
      },
      "required": [
        "texts",
        "steps"
      ],
      "additionalProperties": false,
      "x-vanillasky": {
        "allowsStockMedia": true
      }
    }
  },
  {
    "label": "Triple stats",
    "description": "Exactly three peer values and labels appear as a balanced metric row.",
    "usesGlobalTextEffect": false,
    "usesGlobalTransition": true,
    "usesGlobalBackgroundEffect": true,
    "id": "tripleStats",
    "family": "Data & metrics",
    "jobs": [
      "claim",
      "proof"
    ],
    "register": "typography-led",
    "useWhen": "Exactly three grounded peer metrics or compact specs carry comparable importance.",
    "avoidWhen": "One value is the hero, the values are not comparable, or fewer than three grounded facts exist.",
    "transitionTiming": {
      "entryReadyProgress": 0.2,
      "holdProgress": 0.7
    },
    "textCanvas": "tight",
    "minDuration": 2,
    "preferredDuration": 3,
    "timing": {
      "contentFields": [
        "texts",
        "stat1Label",
        "stat2Label",
        "stat3Label"
      ],
      "contentUnit": "words"
    },
    "schema": {
      "type": "object",
      "properties": {
        "texts": {
          "type": "string",
          "title": "Text",
          "description": "Concise title above the three metrics (48 characters maximum).",
          "minLength": 1,
          "maxLength": 48,
          "default": "By the numbers."
        },
        "stat1Value": {
          "type": "string",
          "title": "Stat 1 value",
          "description": "First compact stat value (e.g. 10K, 99.9%, $2M; 12 characters maximum).",
          "minLength": 1,
          "maxLength": 12,
          "default": "10K"
        },
        "stat1Label": {
          "type": "string",
          "title": "Stat 1 label",
          "description": "Short label below the first number (24 characters maximum).",
          "minLength": 1,
          "maxLength": 24,
          "default": "Users"
        },
        "stat2Value": {
          "type": "string",
          "title": "Stat 2 value",
          "description": "Second compact stat value (12 characters maximum).",
          "minLength": 1,
          "maxLength": 12,
          "default": "99.9%"
        },
        "stat2Label": {
          "type": "string",
          "title": "Stat 2 label",
          "description": "Short label below the second number (24 characters maximum).",
          "minLength": 1,
          "maxLength": 24,
          "default": "Uptime"
        },
        "stat3Value": {
          "type": "string",
          "title": "Stat 3 value",
          "description": "Third compact stat value (12 characters maximum).",
          "minLength": 1,
          "maxLength": 12,
          "default": "<50ms"
        },
        "stat3Label": {
          "type": "string",
          "title": "Stat 3 label",
          "description": "Short label below the third number (24 characters maximum).",
          "minLength": 1,
          "maxLength": 24,
          "default": "Latency"
        },
        "mediaUrl": {
          "type": "string",
          "title": "Background media",
          "description": "Optional photo or video URL behind this scene. When set, replaces the brand gradient.",
          "format": "uri",
          "default": ""
        },
        "mediaKeyword": {
          "type": "string",
          "title": "Background search keyword",
          "description": "2-4 word English term for Pexels stock-footage search (auto-fills mediaUrl).",
          "format": "stock-media-keyword",
          "default": ""
        },
        "mediaType": {
          "type": "string",
          "title": "Background media type",
          "description": "auto detects photo/video from URL. 'gradient' is a deliberate mode — atmospheric brand-color scene with no stock footage.",
          "enum": [
            "auto",
            "photo",
            "video",
            "gradient"
          ],
          "default": "auto"
        },
        "mediaPoster": {
          "type": "string",
          "title": "Background poster image",
          "description": "Still image URL shown while a video backdrop is decoding its first frame. Auto-filled from Pexels' thumbnail when fillPexelsUrls sets a video mediaUrl. Hides the gradient flash that would otherwise appear in the ~50–400ms gap between a <video> mounting and decoding its first frame.",
          "format": "uri",
          "default": ""
        },
        "mediaPosition": {
          "type": "string",
          "title": "Background focal position",
          "description": "Controls which part of a photo or video stays visible when cover-cropped. Pick the subject's side or vertical anchor after inspecting the frame.",
          "enum": [
            "center",
            "top",
            "bottom",
            "left",
            "right"
          ],
          "default": "center"
        },
        "mediaTreatment": {
          "type": "string",
          "title": "Background contrast treatment",
          "description": "none leaves the picture untouched, for a scene carrying no type; subtle preserves a visual hero; cinematic adds balanced contrast; text-safe adds a stronger wash for copy-heavy scenes.",
          "enum": [
            "none",
            "subtle",
            "cinematic",
            "text-safe"
          ],
          "default": "cinematic"
        }
      },
      "required": [
        "texts",
        "stat1Value",
        "stat1Label",
        "stat2Value",
        "stat2Label",
        "stat3Value",
        "stat3Label"
      ],
      "additionalProperties": false,
      "x-vanillasky": {
        "requiresStat": true,
        "allowsStockMedia": true
      }
    }
  }
];
export const templates = createServerTemplateRegistry({ templates: templateMetadata });
