import { anthropic } from "@ai-sdk/anthropic";
import { createFal } from "@ai-sdk/fal";
import { createXai } from "@ai-sdk/xai";
import { experimental_generateSpeech as generateSpeech, experimental_generateVideo as generateVideo, generateText, streamText } from "ai";
import { createVideoHandler } from "@vanillaskyai/video/server";
// Generated by `vanillasky add`: the real templates, and the metadata that
// tells the planner when each one fits.
import { templates } from "./vanillasky/server";
import type { VideoScene } from "@vanillaskyai/video";

/**
 * The two routes a tutor needs.
 *
 * `/api/lesson` plans the scenes and resolves any media they ask for.
 * `/api/narration` writes what is said over them - given the scenes, never the
 * question, because a script written from the question drifts from the
 * composition that was actually chosen.
 *
 * Mounted by the Vite dev server in `vite.config.ts`, so this example runs from
 * one command. In production these are ordinary routes on your own server; the
 * only thing that must not move is the key.
 */
const PLANNER_MODEL = process.env.ANTHROPIC_PLANNER_MODEL ?? "claude-sonnet-5";
const NARRATION_MODEL = process.env.ANTHROPIC_NARRATION_MODEL ?? "claude-haiku-4-5";
const VIDEO_MODEL = process.env.FAL_VIDEO_MODEL ?? "minimax/h3-max/text-to-video";
/**
 * Say one line, properly.
 *
 * The browser's own synthesiser needs no key and sounds like it. A speech model
 * is a separate choice from the video provider - there is no reason a tutor
 * that films with one vendor should speak with it - so this reads its own key
 * and any `SpeechModelV4` would do.
 *
 * A lesson is composed before it plays, so every line is known in advance and
 * can be generated while the scene before it is still on screen. That is why a
 * speech model beats the realtime session this replaced, on both quality and
 * cost: realtime exists to start talking before you know what you will say.
 */
export async function speakLine(request: Request): Promise<Response> {
  const { text } = await request.json() as { text?: string };
  if (!text?.trim()) return new Response("Nothing to say", { status: 400 });
  if (!process.env.XAI_API_KEY) return new Response("Set XAI_API_KEY to hear a real voice", { status: 404 });

  const speech = await generateSpeech({
    model: createXai({ apiKey: process.env.XAI_API_KEY }).speech(),
    text: text.trim(),
  });
  return new Response(speech.audio.uint8Array as unknown as BodyInit, {
    headers: { "content-type": speech.audio.mediaType || "audio/mpeg", "cache-control": "no-store" },
  });
}

/**
 * Film one beat.
 *
 * The planner asks for a subject; every constraint is the host's. A model that
 * writes its own text into the frame competes with the caption over it, and one
 * that adds a voice talks over the narrator.
 */
async function filmScene(subject: string, generatedLook: string | undefined, signal: AbortSignal) {
  const fal = createFal({ apiKey: process.env.FAL_KEY });
  const result = await generateVideo({
    model: fal.video(VIDEO_MODEL),
    prompt: [
      `Locked-off shot, 16:9. ${subject}.`,
      "One slow continuous camera move. Physically plausible motion.",
      "No on-screen text, captions, subtitles, watermarks or logos.",
      "Diegetic sound only. No music, no voiceover.",
      generatedLook,
    ].filter(Boolean).join("\n\n"),
    duration: 5,
    resolution: "854x480",
    // The clip stays where the provider put it: a scene stores an address, so
    // pulling the bytes through this process would be wasted work.
    download: async () => ({ data: new Uint8Array(), mediaType: "video/mp4" }),
    abortSignal: signal,
  });
  const url = result.providerMetadata?.fal?.videos?.[0]?.url;
  if (typeof url !== "string") throw new Error("the video provider returned no url");
  return url;
}

/**
 * One handler per visual mode.
 *
 * The mode is a ceiling on how many scenes may be filmed, and a ceiling is a
 * handler option rather than request input - a client that could raise its own
 * spending limit would not be a limit.
 */
const handlers = new Map<number, ReturnType<typeof createVideoHandler>>();

function lessonHandler(filmedScenes: number) {
  const existing = handlers.get(filmedScenes);
  if (existing) return existing;

  const handler = createVideoHandler({
    authorize: (request) => new URL(request.url).hostname === "localhost",
    // The planner must only choose templates this page can render.
    templates,
    streamText: ({ systemPrompt, userPrompt, signal }) => streamText({
      model: anthropic(PLANNER_MODEL),
      system: systemPrompt,
      prompt: userPrompt,
      abortSignal: signal,
      // Planning is structure, not reasoning, and the current models think
      // adaptively unless told otherwise. Left on the default this took over a
      // minute to emit its first planned scene; off, the whole plan streams in
      // under ten seconds.
      providerOptions: {
        anthropic: {
          thinking: { type: "disabled" },
          output_config: { effort: "medium" },
        },
      },
    }),
    maxResolvedMedia: filmedScenes,
    // Beats film in parallel: waiting for each in turn would make a five-scene
    // lesson half a minute of nothing.
    mediaConcurrency: 4,
    allowMediaUrl: (url) => new URL(url).hostname.endsWith(".fal.media"),
    resolveMedia: filmedScenes === 0 || !process.env.FAL_KEY
      ? undefined
      : async (query, { generatedLook, signal }) => ({
          url: await filmScene(query, generatedLook, signal),
          type: "video" as const,
        }),
  });
  handlers.set(filmedScenes, handler);
  return handler;
}

export function planLesson(request: Request): Promise<Response> {
  const filmed = Number(new URL(request.url).searchParams.get("filmed") ?? 0);
  return lessonHandler(Number.isFinite(filmed) ? Math.max(0, Math.min(8, filmed)) : 0)(request);
}

/**
 * One line for one scene.
 *
 * Narrating scene by scene is what lets the first one play in seconds rather
 * than after the whole plan. The lines already written come with it, so the
 * script joins up instead of reading as unrelated remarks.
 */
const NARRATION_SYSTEM = [
  "You narrate a short explainer video, one scene at a time.",
  "You are given the scene about to be shown, and the lines already said before it.",
  "",
  "Return only the line to say over this scene. No JSON, no quotes, no preamble.",
  "One or two sentences, 12-30 words, plain spoken English.",
  "Say what the scene shows and why it matters. Never read the on-screen text back word for word - the viewer can already see it.",
  "Continue naturally from the lines before it. Never mention scenes, videos or slides.",
].join("\n");

export async function narrateLesson(request: Request): Promise<Response> {
  const payload = await request.json() as { question?: string; scene?: VideoScene; earlier?: string[] };
  if (!payload.scene) return Response.json({ error: "No scene to narrate." }, { status: 400 });

  const earlier = (payload.earlier ?? []).slice(-4);
  const { text } = await generateText({
    model: anthropic(NARRATION_MODEL),
    system: NARRATION_SYSTEM,
    maxOutputTokens: 256,
    prompt: [
      `QUESTION: ${payload.question ?? ""}`,
      earlier.length > 0 ? `\nSAID SO FAR:\n${earlier.map((line) => `- ${line}`).join("\n")}` : "",
      `\nTHIS SCENE: [${payload.scene.templateId}] ${JSON.stringify(payload.scene.variables).slice(0, 400)}`,
    ].join("\n"),
  });
  return Response.json({ line: text.trim().replace(/^["']|["']$/g, "") });
}

const FOLLOWUPS_SYSTEM = [
  "You suggest what a learner would ask next, having just heard an explanation.",
  'Return JSON only: {"followups": string[]} with exactly three short questions.',
  "Make them specific to what was explained, never generic.",
].join("\n");

export async function suggestFollowups(request: Request): Promise<Response> {
  const payload = await request.json() as { question?: string; lines?: string[] };
  try {
    const { text } = await generateText({
      model: anthropic(NARRATION_MODEL),
      system: FOLLOWUPS_SYSTEM,
      maxOutputTokens: 512,
      prompt: `QUESTION: ${payload.question ?? ""}\n\nEXPLANATION:\n${(payload.lines ?? []).join("\n")}`,
    });
    const parsed = JSON.parse(text.slice(text.indexOf("{"), text.lastIndexOf("}") + 1)) as { followups?: unknown };
    const followups = (Array.isArray(parsed.followups) ? parsed.followups : [])
      .filter((entry): entry is string => typeof entry === "string" && entry.trim().length > 0)
      .slice(0, 3);
    return Response.json({ followups });
  } catch {
    // Suggestions are a convenience; a lesson without them is still a lesson.
    return Response.json({ followups: [] });
  }
}
