// App-owned media generation for VanillaSky scenes.
//
// VanillaSky never generates media and never selects a provider. It calls
// `resolveMedia` with a bounded query and the scene being resolved; the
// application decides what to generate, where to store it, and what it costs.
//
// This adapter is provider-neutral: it takes AI SDK model instances rather
// than naming a vendor, so the same code runs against any image or video
// model the AI SDK supports. Choose the provider where you build the models,
// not here.
import { experimental_generateVideo, generateImage, type ImageModel } from "ai";
import type { MediaResolver, MediaResolverContext, ResolvedMedia } from "@vanillaskyai/video/server";

// `ai` declares its video model and provider-option types internally without
// exporting them, so derive them from the call signatures instead of naming
// them. This keeps the adapter correct across AI SDK releases.
type VideoModel = Parameters<typeof experimental_generateVideo>[0]["model"];
type ProviderOptions = Parameters<typeof generateImage>[0]["providerOptions"];

/** Persist generated bytes and return a URL the player can load. */
export type StoreGeneratedMedia = (media: {
  data: Uint8Array;
  mediaType: string;
  kind: "image" | "video";
  /** Stable per scene, so a retried request reuses the stored object. */
  idempotencyKey: string;
}) => Promise<{ url: string }>;

export interface GeneratedMediaOptions {
  imageModel: ImageModel;
  /** Omit to resolve every scene as an image. */
  videoModel?: VideoModel;
  store: StoreGeneratedMedia;
  /** Provider-specific settings, passed straight through to the AI SDK. */
  providerOptions?: ProviderOptions;
}

function aspectRatio(context: MediaResolverContext): "16:9" | "9:16" {
  return context.input.orientation === "portrait" ? "9:16" : "16:9";
}

// One generated asset per scene, keyed so a retry of the same request cannot
// be billed twice.
function idempotencyKey(context: MediaResolverContext): string {
  return `${context.requestId}:${context.scene.id}`;
}

export function createGeneratedMediaResolver(options: GeneratedMediaOptions): MediaResolver {
  return async (query, context): Promise<ResolvedMedia | null> => {
    const wantsVideo = context.preferredType === "video" && options.videoModel !== undefined;

    if (wantsVideo && options.videoModel) {
      const result = await experimental_generateVideo({
        model: options.videoModel,
        prompt: query,
        aspectRatio: aspectRatio(context),
        // Generated media is billable. A silent retry can produce a second
        // charge for one scene, so retries stay an explicit, budget-aware
        // decision in the application rather than an SDK default.
        maxRetries: 0,
        abortSignal: context.signal,
        providerOptions: options.providerOptions,
      });
      const stored = await options.store({
        data: result.video.uint8Array,
        mediaType: result.video.mediaType,
        kind: "video",
        idempotencyKey: idempotencyKey(context),
      });
      return { url: stored.url, type: "video" };
    }

    const result = await generateImage({
      model: options.imageModel,
      prompt: query,
      aspectRatio: aspectRatio(context),
      n: 1,
      maxRetries: 0,
      abortSignal: context.signal,
      providerOptions: options.providerOptions,
    });
    const stored = await options.store({
      data: result.image.uint8Array,
      mediaType: result.image.mediaType,
      kind: "image",
      idempotencyKey: idempotencyKey(context),
    });
    return { url: stored.url, type: "image" };
  };
}
